spring:
  liquibase:
    enabled: true
  application:
    name: pc-assembler
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
logging:
  level:
    sql: debug

## env
minio:
  root:
    user: ${MINIO_ROOT_USER}
    password: ${MINIO_ROOT_PASSWORD}
